version: '1.0'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - anubis
  anubis:
    image: ghcr.io/techarohq/anubis
    ports:
      - "8923:8923"
    environment:
      - DIFFICULTY=4
      - TARGET=http://frontend:3000
    depends_on:
      - frontend